name: 360-enterprise-security
fingerprint:
- path: /
  request_method: get
  request_headers: {}
  request_data: ''
  status_code: 0
  headers: {}
  keyword:
  - 360entinst
  - 关于全网部署360私有云的通知
  priority: 3
- path: /
  request_method: get
  request_headers: {}
  request_data: ''
  status_code: 0
  headers: {}
  keyword:
  - 天擎
  priority: 3
