name: avaya-application-enablement-services
fingerprint:
- path: /
  request_method: get
  request_headers: {}
  request_data: ''
  status_code: 0
  headers: {}
  keyword:
  - <b>application enablement services&nbsp;</b>
  priority: 2
- path: /
  request_method: get
  request_headers: {}
  request_data: ''
  status_code: 0
  headers: {}
  keyword:
  - avaya
  priority: 2
