name: chinatelecomequipmentwebconfigurationsystem
fingerprint:
- path: /
  request_method: get
  request_headers: {}
  request_data: ''
  status_code: 0
  headers: {}
  keyword:
  - 设备web配置</font
  priority: 3
