name: gzsa-intranet-security
fingerprint:
- path: /
  request_method: get
  request_headers: {}
  request_data: ''
  status_code: 0
  headers: {}
  keyword:
  - gzsa. all rights reserved</span>
  priority: 3
