name: gzsa-intranet-security
fingerprint:
- path: /
  status_code: 0
  headers: {}
  keyword:
  - gzsa. all rights reserved</span>
  favicon_hash: []
  priority: 3
  request_method: get
  request_data: ''
  request_headers: {}
