name: jurassic-application-management-system
fingerprint:
- path: /
  request_method: get
  request_headers: {}
  request_data: ''
  status_code: 0
  headers: {}
  keyword:
  - var _usermenusurl = '/appcenter/functions/getusermenu'
  priority: 3
- path: /
  request_method: get
  request_headers: {}
  request_data: ''
  status_code: 0
  headers: {}
  keyword:
  - jurassic
  priority: 3
