name: manageengine-applications-manager
fingerprint:
- path: /
  status_code: 0
  headers: {}
  keyword:
  - /appmanager.js
  favicon_hash: []
  priority: 3
  request_method: get
  request_header: {}
  request_data: null
