name: mission-control-application-shield
fingerprint:
- path: /
  status_code: 0
  headers: {}
  keyword:
  - alt="mission control application shield
  favicon_hash: []
  priority: 3
  request_method: get
  request_header: {}
  request_data: null
