name: mission-control-application-shield
fingerprint:
- path: /
  request_method: get
  request_headers: {}
  request_data: ''
  status_code: 0
  headers: {}
  keyword:
  - alt="mission control application shield
  priority: 3
