name: sap-web-application-server
fingerprint:
- path: /
  status_code: 0
  headers:
    Server: sap web application server
  keyword: []
  favicon_hash: []
  priority: 2
  request_method: get
  request_data: ''
  request_headers: {}
- path: /
  status_code: 0
  headers:
    Server: sap netweaver application server
  keyword: []
  favicon_hash: []
  priority: 2
  request_method: get
  request_data: ''
  request_headers: {}
- path: /
  status_code: 0
  headers:
    Server: sap j2ee engine
  keyword: []
  favicon_hash: []
  priority: 2
  request_method: get
  request_data: ''
  request_headers: {}
