name: sap-web-application-server
fingerprint:
- path: /
  request_method: get
  request_headers: {}
  request_data: ''
  status_code: 0
  headers:
    Server: sap web application server
  keyword: []
  priority: 2
- path: /
  request_method: get
  request_headers: {}
  request_data: ''
  status_code: 0
  headers:
    Server: sap netweaver application server
  keyword: []
  priority: 2
- path: /
  request_method: get
  request_headers: {}
  request_data: ''
  status_code: 0
  headers:
    Server: sap j2ee engine
  keyword: []
  priority: 2
