name: swagger
fingerprint:
- path: /
  status_code: 0
  headers: {}
  keyword:
  - Swagger UI
  favicon_hash: []
  priority: 3
  request_method: get
  request_data: ''
  request_headers: {}
- path: /
  status_code: 0
  headers: {}
  keyword:
  - swagger-ui.css
  favicon_hash: []
  priority: 2
  request_method: get
  request_data: ''
  request_headers: {}
- path: /
  status_code: 0
  headers: {}
  keyword:
  - swagger-ui.js
  favicon_hash: []
  priority: 2
  request_method: get
  request_data: ''
  request_headers: {}
