name: symantec-client-security
fingerprint:
- path: /
  request_method: get
  request_headers: {}
  request_data: ''
  status_code: 0
  headers: {}
  keyword:
  - <!-- symantec client security web based installation -->
  priority: 3
