name: vrv-desktop-application-system
fingerprint:
- path: /
  request_method: get
  request_headers: {}
  request_data: ''
  status_code: 0
  headers: {}
  keyword:
  - <span id="lblvalidcompany" class="validcompany">vrv
  priority: 3
- path: /
  request_method: get
  request_headers: {}
  request_data: ''
  status_code: 0
  headers: {}
  keyword:
  - var vver = $('#hidverify').val();
  priority: 3
